version: "3.7"

services:
  elasticsearch:
    build: .
    volumes:
        - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
    networks:
      - elk

  kibana:
    image: kibana:7.10.1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    # environment:
    #   SERVER_NAME: kibana
    #   ELASTICSEARCH_HOSTS: <http://elasticsearch:9200>
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
    data01:
        driver: local